In [1]:
import pandas as pd
import numpy as np

C:\Users\redyo\AppData\Local\Temp\ipykernel_16576\2937650959.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:

df = pd.read_csv('football_players.csv', encoding='latin1')
print(df.shape)
print(df.columns)
df.head()

(17981, 40)
Index(['Name', 'Age', 'Nationality', 'Overall', 'Acceleration', 'Aggression',
       'Agility', 'Balance', 'Ball control', 'Composure', 'Crossing', 'Curve',
       'Dribbling', 'Finishing', 'Free kick accuracy', 'GK diving',
       'GK handling', 'GK kicking', 'GK positioning', 'GK reflexes',
       'Heading accuracy', 'Interceptions', 'Jumping', 'Long passing',
       'Long shots', 'Marking', 'Penalties', 'Positioning', 'Reactions',
       'Short passing', 'Shot power', 'Sliding tackle', 'Sprint speed',
       'Stamina', 'Standing tackle', 'Strength', 'Vision', 'Volleys',
       'Preferred Positions', 'Preferred Positions Type'],
      dtype='object')

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
0,Cristiano Ronaldo,32,Portugal,94.0,89.0,63.0,89.0,63.0,93.0,95.0,...,94.0,23.0,91.0,92.0,31.0,80.0,85.0,88.0,ST LW,Forward
1,L. Messi,30,Argentina,93.0,92.0,48.0,90.0,95.0,95.0,96.0,...,85.0,26.0,87.0,73.0,28.0,59.0,90.0,85.0,RW,Forward
2,Neymar,25,Brazil,92.0,94.0,56.0,96.0,82.0,95.0,92.0,...,80.0,33.0,90.0,78.0,24.0,53.0,80.0,83.0,LW,Forward
3,L. Suárez,30,Uruguay,92.0,88.0,78.0,86.0,60.0,91.0,83.0,...,87.0,38.0,77.0,89.0,45.0,80.0,84.0,88.0,ST,Forward
4,M. Neuer,31,Germany,92.0,58.0,29.0,52.0,35.0,48.0,70.0,...,25.0,11.0,61.0,44.0,10.0,83.0,70.0,11.0,GK,GoalKeeper

In [3]:
print(df[df['Nationality'] == 'Algeria']['Overall'].shape)
df[df['Nationality'] == 'Algeria']['Overall'].idxmax

(57,)

<bound method Series.idxmax of 143      83.0
202      82.0
259      82.0
356      81.0
396      80.0
577      79.0
629      79.0
775      78.0
862      78.0
1065     77.0
1371     76.0
1504     76.0
1750     75.0
1778     75.0
1890     75.0
1940     75.0
3006     73.0
3094     73.0
3199     73.0
3469     72.0
3486     72.0
3513     72.0
4187     71.0
4310     71.0
4499     71.0
4608     71.0
4635     71.0
4804     71.0
4881     70.0
5127     70.0
5160     70.0
5693     70.0
5953     69.0
5959     69.0
6177     69.0
6212     69.0
6380     69.0
6750     68.0
7043     68.0
7061     68.0
7437     68.0
7509     68.0
7532     68.0
7838     67.0
8434     67.0
8889     66.0
8964     66.0
9526     66.0
9764     66.0
10241    65.0
10311    65.0
10595    65.0
10956    64.0
11259    64.0
13480    62.0
13544    62.0
17192    54.0
Name: Overall, dtype: float64>

In [4]:
# df[df['Nationality'] == 'Algeria']['Nationality'].value_counts
df[df['Nationality'] == 'Algeria']['Overall'].idxmax() #->143
# df[df['Nationality']=='Algeria']['Name'].[143]
df['Name'].iloc[143]

'R. Mahrez'

In [12]:
max_score = df['Sliding tackle'].idxmax()
df['Name'][10]

'Sergio Ramos'

In [34]:
df.head()

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
0,Cristiano Ronaldo,32,Portugal,94.0,89.0,63.0,89.0,63.0,93.0,95.0,...,94.0,23.0,91.0,92.0,31.0,80.0,85.0,88.0,ST LW,Forward
1,L. Messi,30,Argentina,93.0,92.0,48.0,90.0,95.0,95.0,96.0,...,85.0,26.0,87.0,73.0,28.0,59.0,90.0,85.0,RW,Forward
2,Neymar,25,Brazil,92.0,94.0,56.0,96.0,82.0,95.0,92.0,...,80.0,33.0,90.0,78.0,24.0,53.0,80.0,83.0,LW,Forward
3,L. Suárez,30,Uruguay,92.0,88.0,78.0,86.0,60.0,91.0,83.0,...,87.0,38.0,77.0,89.0,45.0,80.0,84.0,88.0,ST,Forward
4,M. Neuer,31,Germany,92.0,58.0,29.0,52.0,35.0,48.0,70.0,...,25.0,11.0,61.0,44.0,10.0,83.0,70.0,11.0,GK,GoalKeeper

In [24]:
df['Preferred Positions'][df['Preferred Positions'] == 'RW ']

1        RW
15       RW
137      RW
166      RW
230      RW
        ...
17288    RW
17367    RW
17473    RW
17869    RW
17915    RW
Name: Preferred Positions, Length: 91, dtype: object

In [61]:
# df_interest = df.groupby('Preferred Positions')['Overall'].mean()
df_En = df[df['Nationality'] == 'England']
df_En.groupby('Preferred Positions Type')['Overall'].mean().idxmax()

'Back'

Q41

In [60]:
df_Brazil = df[df['Nationality'] == 'Brazil']
df_forward = df_Brazil[df_Brazil['Preferred Positions Type'] == 'Forward']['Overall'].mean()
df_back = df_Brazil[df_Brazil['Preferred Positions Type'] == 'Back']['Overall'].mean()
# df_back = df_Brazil[df_Brazil['Preferred Positions']== 'Forward']
print("Forwards: ", df_forward)
print("Backs:", df_back)
print

Forwards:  70.02890173410404
Backs: 71.49097472924188

Q42 oldest Player

In [63]:
df.head()

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
0,Cristiano Ronaldo,32,Portugal,94.0,89.0,63.0,89.0,63.0,93.0,95.0,...,94.0,23.0,91.0,92.0,31.0,80.0,85.0,88.0,ST LW,Forward
1,L. Messi,30,Argentina,93.0,92.0,48.0,90.0,95.0,95.0,96.0,...,85.0,26.0,87.0,73.0,28.0,59.0,90.0,85.0,RW,Forward
2,Neymar,25,Brazil,92.0,94.0,56.0,96.0,82.0,95.0,92.0,...,80.0,33.0,90.0,78.0,24.0,53.0,80.0,83.0,LW,Forward
3,L. Suárez,30,Uruguay,92.0,88.0,78.0,86.0,60.0,91.0,83.0,...,87.0,38.0,77.0,89.0,45.0,80.0,84.0,88.0,ST,Forward
4,M. Neuer,31,Germany,92.0,58.0,29.0,52.0,35.0,48.0,70.0,...,25.0,11.0,61.0,44.0,10.0,83.0,70.0,11.0,GK,GoalKeeper

In [67]:
maxAge_index = df['Age'].idxmax()
df['Nationality'].iloc[maxAge_index]

'England'

Q43

In [72]:
df_Gk = df[['GK diving','GK handling', 'GK kicking','GK reflexes']]
for i in df_Gk.columns:
    print(f"{i}   {df_Gk[i].mean()}")

GK diving   16.71091707913909
GK handling   16.490517768755907
GK kicking   16.37428396640899
GK reflexes   16.838885490239697

Q44

In [77]:
df['Preferred Positions Type'].value_counts()

Preferred Positions Type
Midfielder    6769
Back          5848
Forward       3253
GoalKeeper    2111
Name: count, dtype: int64

Q45

In [82]:
df_portugal = df[(df['Nationality'] == 'Portugal') & (df['Age'] < 25)]
df_portugal.head()

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
94,Bernardo Silva,22,Portugal,84.0,85.0,58.0,88.0,86.0,89.0,84.0,...,72.0,35.0,78.0,80.0,44.0,54.0,85.0,66.0,RM,Midfielder
133,João Mário,24,Portugal,83.0,71.0,61.0,81.0,70.0,85.0,85.0,...,77.0,61.0,75.0,84.0,75.0,69.0,82.0,69.0,CAM CM,Midfielder
209,André Gomes,23,Portugal,82.0,71.0,81.0,67.0,64.0,80.0,78.0,...,80.0,64.0,66.0,78.0,77.0,85.0,83.0,63.0,CAM LW CM,Midfielder
300,Nélson Semedo,23,Portugal,81.0,91.0,77.0,88.0,83.0,78.0,75.0,...,74.0,78.0,92.0,90.0,77.0,59.0,62.0,42.0,RB,Back
301,Gelson Martins,22,Portugal,81.0,95.0,57.0,94.0,94.0,83.0,84.0,...,72.0,36.0,94.0,87.0,46.0,48.0,78.0,74.0,LM RM,Midfielder

In [90]:
# df_portugal['Name'].iloc[df_portugal['Overall'].idxmax()]
idx = df_portugal['Overall'].idxmax() #->94
idx

94

In [95]:
df['Name'].iloc[idx]

'Bernardo Silva'